require "prototypes/worldgen.lua"
require "prototypes/categories.lua"
require "prototypes/tiles.lua"
require "prototypes/items.lua"
require "prototypes/fluids.lua"
require "prototypes/entities.lua"
require "prototypes/recipes.lua"
