data:extend{
  {
    type = "int-setting",
    name = "pk-oxygen-volume-per-tile",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximim_value = 1000,
  },
  {
    type = "double-setting",
    name = "pk-oxygen-leak-per-tile-per-update",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
  },
  {
    type = "int-setting",
    name = "pk-no-o2-damage-per-second",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
  },
  {
    type = "int-setting",
    name = "pk-no-o2-player-damage-per-second",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
  },
  {
    type = "int-setting",
    name = "pk-no-shielding-damage-per-second",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
  },
}
